const nodemailer = require("nodemailer");

let transporter = nodemailer.createTransport({
  service: "gmail",
  host: "smtp.gmail.com", // true for 465, false for other ports
  auth: {
    user: process.env.MAILERUSER, // generated ethereal user
    pass: process.env.MAILERPASS, // generated ethereal password
  },
});

module.exports = {
  SendOtpUsingMail: async (OTP) => {
    let info = await transporter.sendMail({
      from: process.env.MAILERUSER, // sender address
      to: "satvikshukla453@gmail.com", // list of receivers
      subject: "Hello ✔", // Subject line
      html: `
        <div style="background-color: #cce7ff;padding: 20px;gap: 20px;font-size: 16px">
            This email is generated by MedLife for email verification
            <br/>
            Enter the OTP given below to verify :
            <br/>

            <div style=""> 
            <center style="width:100%">
                <span style="border:2px solid black;padding:10px;font-size: 24px;font-weight:bold;letter-spacing:5px;border-radius:20px;background-color:black;color:white;" > ${OTP} </span>
            <center>
            </div>

        </div>
      `,
    });

    console.log("Message sent: %s", info.messageId);
    return info;
  },
};
